types:
  upstream:
    label: Upstream
    colour: '#cccccc'
  direct:
    label: Total direct production cost
    colour: '#8a4c39'
  capital:
    label: Capital cost
    colour: '#f36f21'
  fonmco:
    label: Fixed operation<br>and maintenance cost
    colour: '#00813e'
  feedstock:
    label: Feedstock cost<br>(non-energy, non-iron)
    colour: '#3745a3'
  iron:
    label: Iron feedstock cost
    colour: '#cccccc'
  energy:
    label: Energy cost
    colour: '#e6af2e'
  transport:
    label: Transport cost
    colour: '#7c1f8a'
  carbon:
    label: Carbon cost from carbon pricing
    colour: '#db2a1a'
  non-energy:
    label: Non-energy cost
    colour: '#3745a3'

components:
  alloys: Alloys
  dri: DRI
  graphite: Graphite
  labour: Labour
  lime: Lime
  natural gas: Natural gas
  electricity: Electricity
  hydrogen: Hydrogen
  onm: Operation and Maintenance
  ore: Iron ore
  scrap: Steel scrap
  steel: Steel
