figS4:
  name: Figure S4
  title: Cost-effectiveness of recycling
  desc:
    'Showing cost as a function of the recylcing share.'
  display:
  - /advanced
  sizes:
    print:
      height: 81.0  # unit mm
      width: 180.0  # unit mm
    webapp:
      height: 600.0  # unit px
      width: 100.0  # unit %
