fig6:
  name: Figure 6
  title: Share of energy cost in value creation.
  desc:
    'Shown is the levelised cost of production of individual process steps along the value chain of the studied 
    energy-intensive goods for the Base Case. Clearly, electrolysis for the production of H₂ and DAC for the winning of 
    CO₂ from the atmosphere are the most energy-intensive steps in all value chains. However, a significant share of 
    energy demand remains in all other processes, especially in the EAF.'
  sizes:
    print:
      height: 81.0  # unit mm
      width: 180.0  # unit mm
    webapp:
      height: 600.0  # unit px
      width: 100.0  # unit %
  display:
  - /
  - /advanced
figS5:
  name: Figure S5
  title: Share of energy cost in value creation.
  desc:
    'Shown is the levelised cost of production of individual process steps along the value chain of the studied 
    energy-intensive goods for the Base Case. Clearly, electrolysis for the production of H₂ and DAC for the winning of 
    CO₂ from the atmosphere are the most energy-intensive steps in all value chains. However, a significant share of 
    energy demand remains in all other processes, especially in the EAF.'
  sizes:
    print:
      height: 81.0  # unit mm
      width: 180.0  # unit mm
    webapp:
      height: 600.0  # unit px
      width: 100.0  # unit %
  display:
  - /advanced
