figED1:
  name: Extended Data Fig. 1
  title: Dependence of the production-cost difference on the electricity-price difference and the H₂ transportation cost.
  desc:
    'Top: The cost difference between Cases 1–3 and the Base Case increases linearly with the electricity-price 
    difference. The secondary Y-Axes show the production-cost difference relative to the total production cost in the 
    Base Case. Bottom: Heatmap show the production cost difference as a function of both electricity-price difference 
    and H₂ transportation cost for Case 1, with the red line showing the default assumption for Case 1B from the top. 
    The dashed line indicates the electricity-price difference for the default assumptions used to produce the data in 
    Fig. 1.'
  sizes:
    print:
      height: 180.0  # unit mm
      width: 180.0  # unit mm
    webapp:
      height: 1200.0  # unit px
      width: 100.0  # unit %
  display:
  - /advanced
