figED1:
  name: Extended Data Fig. 1
  title: 'Sensitivity analysis for the three studied commodities (left-to-right: steel, urea, ethylene).'
  desc:
    'The estimations of the relocation savings shown in Figs. 4 and 5 are analysed with respect to alternative 
     assumptions for the electricity price, specific H<sub>2</sub> transport cost, and weighted-average cost of capital 
     (WACC). First row: relocation savings as a function of WACC in the RE-rich region for the ‘medium pull’ 
     electricity-price case from Tab. 1. Second row: relocation savings as a function of specific H<sub>2</sub> 
     transport cost for Case 1 from Fig. 3. Third row: relocation savings as a function of electricity-price 
     difference. Fourth row: relocation savings as a function of both electricity-price difference and specific 
     H<sub>2</sub> transport cost.'
  sizes:
    print:
      height: 180.0  # unit mm
      width: 180.0  # unit mm
    webapp:
      height: 1200.0  # unit px
      width: 100.0  # unit %
  display:
  - /advanced
