fig3:
  name: Figure 3
  title: Total cost reductions.
  desc:
    'Description to be written.'
  display:
  - /
  - /advanced
  sizes:
    print:
      height: 81.0  # unit mm
      width: 180.0  # unit mm
    webapp:
      height: 600.0  # unit px
      width: 100.0  # unit %
