commodity_colours:
  Steel: '#57656c'
  Urea: '#228f9c'
  Ethylene: '#8f5635'

case_names:
  Base Case: Heimische<br>Produktion
  Case 1: Import v. H<sub>2</sub><br>per Schiff/<br>Pipeline
  Case 2: Import v.<br>Zwischen-<br>produkten
  Case 3: Import v.<br>(halb-)fertigen<br>Produkten

cost_types:
  capital:
    label: Annualisierte<br>Kapitalkosten
    colour: '#8f3547'
  fonmco:
    label: Betriebs- und<br>Wartungskosten
    colour: '#3c7d2c'
  rawmat:
    label: Rohmaterial-<br>kosten
    colour: '#cdd1d3'
  energy:
    label: Nicht-elek.<br>Energiekosten
    colour: '#899297'
  elec:
    label: Stromkosten
    colour: '#ecc15d'
  transport:
    label: Transportkosten
    colour: '#5f4491'

components:
  alloys: Alloys
  dri: DRI
  graphite: Graphite
  labour: Labour
  lime: Lime
  natural gas: Natural gas
  electricity: Electricity
  hydrogen: Hydrogen
  onm: Operation and Maintenance
  ore: Iron ore
  scrap: Steel scrap
  steel: Steel
