title: Estimating the renewables pull in future global green value chains
desc:
  This webapp reproduces results presented in an accompanying manuscript on estimations of the renewables pull in 
  future global green value chains. It determines energy-cost savings and other relocation penalties based for 
  different import scenarios for the green value chains of steel, urea, and ethylene.
auth: Philipp C. Verpoort, Lukas Gast, Anke Hofmann, Falko Ueckerdt
date: 25/03/2023
