title: The renewables pull in future global green value chains
desc:
  Techno-economic assessment of import scenarios for selected energy-intensive goods (steel, urea, ethylene) based on 
  price differences for renewable electricity.
auth: Philipp C. Verpoort, Anke Hofmann, Lukas Gast, Falko Ueckerdt
date: 18/11/2022
figures:
  fig3: [/, /advanced]
  fig4: [/, /advanced]
  fig5: [/, /advanced]
  fig6: [/, /advanced]
  figS1: [/advanced]
  figS2: [/advanced]
  figS3: [/advanced]
  figS4: [/advanced]
