title: The renewables pull in future global green value chains
desc:
  Techno-economic assessment of import scenarios for selected energy-intensive goods (steel, urea, ethylene) based on 
  price differences for renewable electricity.
auth: Philipp C. Verpoort, Anke Hofmann, Lukas Gast, Falko Ueckerdt
date: 14/02/2023
