types:
  upstream:
    label: Upstream
    colour: '#cccccc'
  capital:
    label: Capital
    colour: '#f36f21'
  fonmco:
    label: Operation and maintenance
    colour: '#00813e'
  feedstock:
    label: Non-energy feedstock
    colour: '#cccccc'
  iron:
    label: Iron feedstock
    colour: '#cccccc'
  energy:
    label: Energy
    colour: '#e6af2e'
  transport:
    label: Transport
    colour: '#7c1f8a'
#  carbon:
#    label: Carbon cost from carbon pricing
#    colour: '#db2a1a'
#  direct:
#    label: Total direct production cost
#    colour: '#8a4c39'
#  non-energy:
#    label: Non-energy cost
#    colour: '#3745a3'

components:
  alloys: Alloys
  dri: DRI
  graphite: Graphite
  labour: Labour
  lime: Lime
  natural gas: Natural gas
  electricity: Electricity
  hydrogen: Hydrogen
  onm: Operation and Maintenance
  ore: Iron ore
  scrap: Steel scrap
  steel: Steel
