figures:
  fig6:
    name: Fig. 6
    title: Estimates of annual green-relocation protection for Germany.
    desc:
      'We assume the scenarios outlined in Tab. 2 and apply the generic framework for production-cost estimates presented 
      in the previous section. The three columns correspond to the three cases for electricity-price differences (weak, 
      medium, and strong pull) in Tab. 1.'
    display:
    - ''
    size:
      print:
        width: 180.0  # unit mm
        height: 80.0  # unit mm
      webapp:
        width: 100.0  # unit %
        height: 600.0  # unit px
config:
  yaxis_title:
    left: Möglicher Green-Relocation-Schutz Mechanismus (Mrd. EUR/a)
    right: Geplante Ausgaben auf Bundesebene (Mrd. EUR/a)
  yaxis_max: 26.0

  legendgroup_titles:
    protection: Mögl. Green-Relocation-<br>Schutz Mechanismus
    existing: Geplante Ausgaben<br>auf Bundesebene

  epdcases: ['weak', 'medium', 'strong']

  expenses_color:
    Klima- und Trans-<br>formationsfonds (KTF): '#E4EAEA'
    Bundeshaushalt: '#a2b6b6'

  scenario_names:
    Scen 1: <b>Scenario 1</b><br>Fokus auf Import<br>von H<sub>2</sub>
    Scen 2: <b>Scenario 2</b><br>Fokus auf Import<br>von Zwischenprodukten

  planned_expenses:
    EEG:
      label: EEG-Umlage
      type: Klima- und Trans-<br>formationsfonds (KTF)
      value: 12.6
    Gebaeude:
      label: Gebäude-<br>förderung
      type: Klima- und Trans-<br>formationsfonds (KTF)
      value: 18.9
    BMWK:
      label: BMWK
      type: Bundeshaushalt
      value: 15.0
    BMBF:
      label: BMBF
      type: Bundeshaushalt
      value: 21.0
    BMG:
      label: BMG
      type: Bundeshaushalt
      value: 24.0
