figures:
  figED1:
    name: Ext. Data Figure 1
    title: Sensitivity analysis.
    desc:
      'Shown are the main results from Fig. 4 with electricity-price difference of 40 EUR/MWh, while varying the WACC on 
      the RE-rich exporter between 5% and 20% (a--c), rel.~changes in CAPEX between -50% and +100% (d--f), tranpost cost 
      for H<sub>2</sub> between 5 EUR/MWh and 90 EUR/MWh (g--i), whether the heat for DAC is provided by a heatpump or 
      not (j--k), and whether existing grey plants (hot rolling in steel, Haber-Bosch, urea synth.) can be repurposed 
      (l--m).'
    display:
    - 'ext-data'
    size:
      print:
        width: 180.0  # unit mm
        height: 140.0  # unit mm
      webapp:
        width: 100.0  # unit %
        height: 1200.0  # unit px
config:
  epdcase: medium

  symbol: x-thin
  symbolCase1A: triangle-up

  yaxis_title: Production cost relative to Base Case (%)
  yaxis:
    range:
      - 0.0
      - 125.0
    tick0: -60.0
    dtick: 20.0
    showgrid: True
    griddash: dash
    gridcolor: '#CCCCCC'

  senstypes:
    wacc:
      label: WACC for RE-<br>rich exporter
    capex:
      label: Rel. increase<br>of CAPEX
    h2transp:
      label: H<sub>2</sub> transport<br>cost
    dachp:
      label: DAC energy<br>demand
    repurpose:
      label: Repurposing grey<br>production plants
