fig7:
  name: Fig. 7
  title: Estimates of annual green-relocation protection for Germany.
  desc:
    'We assume the scenarios outlined in Tab. 2 and apply the generic framework for production-cost estimates presented 
    in the previous section. The three columns correspond to the three cases for electricity-price differences (weak, 
    medium, and strong pull) in Tab. 1.'
  display:
  - 'advanced'
  size:
    print:
      width: 180.0  # unit mm
      height: 80.0  # unit mm
    webapp:
      width: 100.0  # unit %
      height: 600.0  # unit px
  config:
    yaxis_title:
      left: Potential annual green-relocation protection (bn EUR/a)
      right: Planned federal fiscal spending (bn EUR/a)
    yaxis_max: 26.0

    legendgroup_titles:
      protection: Potential green-relocation<br>protection scheme
      existing: Planned federal fiscal<br>spending

    epdcases: ['weak', 'medium', 'strong']

    expenses_color:
      Special budget: '#cccccc'
      Regular budget: '#aaaaaa'

    scenario_names:
      Scen 1: <b>Scenario 1</b><br>Focus H<sub>2</sub>
      Scen 2: <b>Scenario 2</b><br>Focus intermediates

    planned_expenses:
      EEG:
        label: Renewables<br>support
        type: Special budget
        value: 12.6
      Gebaeude:
        label: Buildings<br>renovations
        type: Special budget
        value: 18.9
      BMWK:
        label: Ministry of<br>Economic<br>Affairs
        type: Regular budget
        value: 15.0
      BMBF:
        label: Ministry of<br>Research and<br>Education
        type: Regular budget
        value: 21.0
      BMG:
        label: Ministry of<br>Health
        type: Regular budget
        value: 24.0
