fig7:
  name: Fig. 7
  title: Estimates of annual green-relocation protection for Germany.
  desc:
    'We assume the scenarios outlined in Tab. 2 and apply the generic framework for production-cost estimates presented 
    in the previous section. The three columns correspond to the three cases for electricity-price differences (weak, 
    medium, and strong pull) in Tab. 1.'
  display:
  - 'advanced'
  size:
    print:
      height: 80.0  # unit mm
      width: 88.0  # unit mm
    webapp:
      height: 600.0  # unit px
      width: 100.0  # unit %
  config:
    yaxis_title: Annual green-relocation protection (bn EUR/a)

    epdcases: ['weak', 'medium', 'strong']
