yaxislabel: Levelised Cost of Commodities (EUR/t)

simplify_types: True
map_processes: True

select_period: 2050
epdcase: default

import_route:
  Steel: Base Case
  Urea: Base Case
  Ethylene: Base Case

skip_upstream:
  - HP
  - DAC
