top:
  xaxislabel: Process steps along the value chains
  yaxislabel: Share of cost components<br>in total production cost (%)
bottom:
  xaxislabel: Marginal relocation savings relative to the Base Case (%)
  yaxislabel: Share of value added<br>lost in relocation (%)
appendix:
  xaxislabel: Process steps along the value chains
  yaxislabel: Levelised Cost of Commodities (EUR/t)

select_case: Base Case
select_epdcase: default
select_period: 2050

symbol: x-thin

map_processes:
  - HP
  - DAC
show_mapped: False
