xaxislabel: Electricity-price difference (EUR/MWh)
xlabelshort: Elec-price diff
xsamples: 20

top:
  yaxislabel: Production-cost difference (EUR/t)
  ylabelshort: Prod-cost diff

  yaxis2label: Relative to Base Case production cost (%)
bottom:
  yaxislabel: H₂ specific transportation cost (EUR/MWh)
  ylabelshort:  H₂ transp cost
  yrange:
    - 0.0
    - 75.0
  zaxislabel: Relocation savings relative<br>to the Base Case (%)
  zrange:
    - -100.0
    - +100.0
  zdelta: 10.0
  zcolours:
    - '#e6af2e'
    - '#ffffff'
    - '#3745a3'
  zticks:
    - 100
    - 50
    - 0
    - -50
    - -100

samples: 51

symbol: x-thin

line_colour:
  Case 1A: '#db2a1a'
  Case 1B: '#db2a1a'
  Case 2: '#00813e'
  Case 3: '#0000CC'

select_period: 2040
