sensitivity1:
  xaxislabel: Weighted average cost of capital (WACC) in RE-rich region (%)
  xlabelshort: RE-rich WACC
  xrange:
    - 5.0
    - 15.0

  yaxislabel: Total production cost (EUR/t)
  ylabelshort: Tot. prod. cost
  epdcase: medium

sensitivity2:
  xaxislabel: H<sub>2</sub> specific transportation cost (EUR/MWh)
  xlabelshort:  H<sub>2</sub> transp cost
  xrange:
    - 0.0
    - 65.0

  yaxislabel: Total production cost (EUR/t)
  ylabelshort: Tot. prod. cost

sensitivity3:
  xaxislabel: Electricity-price difference (EUR/MWh)
  xlabelshort: Elec-price diff
  yaxislabel: Total production cost (EUR/t)
  ylabelshort: Tot. prod. cost

  yaxis2label: Relative to Base Case production cost (%)
sensitivity4:
  xaxislabel: Electricity-price difference (EUR/MWh)
  xlabelshort: Elec-price diff

  yaxislabel: H<sub>2</sub> specific transportation cost (EUR/MWh)
  ylabelshort:  H<sub>2</sub> transp cost
  yrange:
    - 0.0
    - 65.0
  zaxislabel: Relocation savings relative<br>to the Base Case (%)
  zrange:
    - -100.0
    - +100.0
  zdelta: 10.0
  zcolours:
    - '#e6af2e'
    - '#ffffff'
    - '#3745a3'
  zticks:
    - 100
    - 50
    - 0
    - -50
    - -100

samples: 51

symbol: x-thin

line_colour:
  Case 1A: '#db2a1a'
  Case 1B: '#db2a1a'
  Case 2: '#00813e'
  Case 3: '#0000CC'

select_period: 2040
