top:
  domain_boundary: 0.68
  yaxislabel: Relocation savings relative to the Base Case (%)
  yaxis:
    range:
      - -65.0
      - +25.0
    tick0: -60.0
    dtick: 20.0
    showgrid: True
    griddash: dash
    gridcolor: '#CCCCCC'

bottom:
  domain_boundary: 0.56
  xaxislabel: Renewables-pull savings (EUR/t)
  yaxislabel: Transportation penalty (EUR/t)
  zaxislabel: Relocation savings relative<br>to the Base Case (%)
  zrange:
    - -100.0
    - +100.0
  zdelta: 20.0
  zcolours:
    - '#3745a3'
    - '#ffffff'
    - '#e6af2e'
  zticks:
    - 100
    - 50
    - 0
    - -50
    - -100
  samples: 10

symbol: x-thin
contourLines: False

#symbol:
#  Steel: x-thin
#  Urea: cross-thin
#  Ethylene: circle-open-dot #triangle-up-open

select_period: 2050
